"""create rate limits table

Revision ID: 832692a10dc1
Revises: 46970a2413c4
Create Date: 2026-10-03 21:29:37.595188

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "832692a10dc1"
down_revision: str | None = "46970a2413c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limits",
        sa.Column("key", sa.String(length=400), nullable=False),
        sa.Column("window_start", sa.BigInteger(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(
        op.f("ix_rate_limits_window_start"),
        "rate_limits",
        ["window_start"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rate_limits_window_start"), table_name="rate_limits")
    op.drop_table("rate_limits")
    # ### end Alembic commands ###
