"""Add terms acceptance to users

Revision ID: c70b59cdea39
Revises: eccbc6ae54b7
Create Date: 2026-10-09 10:37:48.150352

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c70b59cdea39"
down_revision: str | None = "eccbc6ae54b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
