"""Add terms acceptance to users

Revision ID: da2f4e30cdcd
Revises: c70b59cdea39
Create Date: 2026-10-09 11:14:09.390454

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "da2f4e30cdcd"
down_revision: str | None = "c70b59cdea39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
