"""Add terms acceptance to users

Revision ID: eccbc6ae54b7
Revises: 832692a10dc1
Create Date: 2026-10-09 10:26:10.380845

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eccbc6ae54b7"
down_revision: str | None = "832692a10dc1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "terms_accepted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "term_version", sa.String(length=50), server_default="1.0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "term_version")
    op.drop_column("users", "terms_accepted_at")
    # ### end Alembic commands ###
